top_view_zoom_factor: 0.36
top_view_pan: '0,5.5,0'
bottom_view_zoom_factor: 0.36
bottom_view_pan: '0,5.5,0'
side_view_zoom_factor: 0.36
side_view_rotate: '315,360,405'
side_view_pan: '0,-1.2,0'
left_view_zoom_factor: 0.6
left_view_pan: '5,-3,0'
right_view_zoom_factor: 0.6
right_view_pan: '5,-3,0'