# KiCad Documentation Generation Configuration

# View definitions - add or remove views as needed
views:
  side:
    prefix: '1_'
    suffix: '_side'
    zoom_factor: 0.3
    rotate: '315,360,405'
    pan: '0,-3,0'
    light_elevation: 30
    side: 'top'  # KiCad side parameter (top, bottom, left, right, front, back)
    
  top:
    prefix: '2_'
    suffix: '_top'
    zoom_factor: 0.35
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'top'
    
  bottom:
    prefix: '3_'
    suffix: '_bottom'
    zoom_factor: 0.35
    rotate: '0,0,0'
    pan: '0,0,0'
    light_elevation: 60
    side: 'bottom'
    
  left:
    prefix: '4_'
    suffix: '_left'
    zoom_factor: 0.6
    rotate: '0,0,0'
    pan: '0,-5,0'
    light_elevation: 10
    side: 'left'
    
  right:
    prefix: '5_'
    suffix: '_right'
    zoom_factor: 0.6
    rotate: '0,0,0'
    pan: '0,-5,0'
    light_elevation: 10
    side: 'right'
    
  front:
    prefix: '6_'
    suffix: '_front'
    zoom_factor: 0.6
    rotate: '0,0,0'
    pan: '0,-5,0'
    light_elevation: 10
    side: 'front'
    
  back:
    prefix: '7_'
    suffix: '_back'
    zoom_factor: 0.6
    rotate: '0,0,0'
    pan: '0,-5,0'
    light_elevation: 10
    side: 'back'
    
  test:
    prefix: '8_'
    suffix: '_back'
    zoom_factor: 0.6
    rotate: '0,0,0'
    pan: '0,-5,0'
    light_elevation: 10
    side: 'back'

# Default values for any unspecified parameters
defaults:
  zoom_factor: 1.0
  rotate: '0,0,0'
  pan: '0,0,0'
  light_elevation: 60
  side: 'top'