picture_prefix_side: '1_'
picture_prefix_top: '2_'
picture_prefix_bottom: '3_'
picture_prefix_left: '4_'
picture_prefix_right: '5_'
picture_prefix_front: '6_'
picture_prefix_back: '7_'
picture_suffix_side: '_side'
picture_suffix_top: '_top'
picture_suffix_bottom: '_bottom'
picture_suffix_left: '_left'
picture_suffix_right: '_right'
picture_suffix_front: '_front'
picture_suffix_back: '_back'
top_view_zoom_factor: 0.35
top_view_pan: '0,0,0'
bottom_view_zoom_factor: 0.35
bottom_view_pan: '0,0,0'
side_view_zoom_factor: 0.3
side_view_rotate: '315,360,405'
side_view_pan: '0,-3,0'
left_view_zoom_factor: 0.6
left_view_pan: '0,-5,0'
right_view_zoom_factor: 0.6
right_view_pan: '0,-5,0'
front_view_zoom_factor: 0.6
front_view_rotate: '0,0,0'
front_view_pan: '0,-5,0'
back_view_zoom_factor: 0.6
back_view_rotate: '0,0,0'
back_view_pan: '0,-5,0'