top_view_zoom_factor: 0.45
top_view_pan: '0,0,0'
bottom_view_zoom_factor: 0.45
bottom_view_pan: '0,0,0'
side_view_zoom_factor: 0.4
side_view_rotate: '315,360,405'
side_view_pan: '0,-3.8,0'
left_view_zoom_factor: 0.6
left_view_pan: '0,-6,0'
right_view_zoom_factor: 0.6
right_view_pan: '0,-6,0'
front_view_zoom_factor: 0.6
front_view_rotate: '0,0,0'
front_view_pan: '0,-6,0'
back_view_zoom_factor: 0.6
back_view_rotate: '0,0,0'
back_view_pan: '0,-6,0'